// <auto-generated />
using System;
using ManagerGame.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ManagerGame.Core.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250508134219_init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ManagerGame.Domain.Draft", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_date");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uuid")
                        .HasColumnName("league_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.HasKey("Id")
                        .HasName("pk_drafts");

                    b.HasIndex("LeagueId")
                        .HasDatabaseName("ix_drafts_league_id");

                    b.ToTable("drafts", (string)null);
                });

            modelBuilder.Entity("ManagerGame.Domain.League", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_date");

                    b.Property<string>("InviteCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("invite_code");

                    b.Property<bool>("IsGroupStageCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_group_stage_completed");

                    b.Property<bool>("IsKnockoutDraftCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_knockout_draft_completed");

                    b.Property<bool>("IsTournamentCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_tournament_completed");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.HasKey("Id")
                        .HasName("pk_leagues");

                    b.ToTable("leagues", (string)null);
                });

            modelBuilder.Entity("ManagerGame.Domain.LeagueSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_date");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uuid")
                        .HasColumnName("league_id");

                    b.Property<int>("MaxPlayersFromSameCountry")
                        .HasColumnType("integer")
                        .HasColumnName("max_players_from_same_country");

                    b.Property<int>("PointsPerAssist")
                        .HasColumnType("integer")
                        .HasColumnName("points_per_assist");

                    b.Property<int>("PointsPerCleanSheet")
                        .HasColumnType("integer")
                        .HasColumnName("points_per_clean_sheet");

                    b.Property<int>("PointsPerGoal")
                        .HasColumnType("integer")
                        .HasColumnName("points_per_goal");

                    b.Property<int>("PointsPerWin")
                        .HasColumnType("integer")
                        .HasColumnName("points_per_win");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.HasKey("Id")
                        .HasName("pk_league_settings");

                    b.HasIndex("LeagueId")
                        .IsUnique()
                        .HasDatabaseName("ix_league_settings_league_id");

                    b.ToTable("league_settings", (string)null);
                });

            modelBuilder.Entity("ManagerGame.Domain.Manager", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.HasKey("Id")
                        .HasName("pk_managers");

                    b.ToTable("managers", (string)null);
                });

            modelBuilder.Entity("ManagerGame.Domain.MatchEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_date");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<bool>("IsHomeTeam")
                        .HasColumnType("boolean")
                        .HasColumnName("is_home_team");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("match_id");

                    b.Property<int>("Minute")
                        .HasColumnType("integer")
                        .HasColumnName("minute");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.HasKey("Id")
                        .HasName("pk_match_events");

                    b.HasIndex("MatchId")
                        .HasDatabaseName("ix_match_events_match_id");

                    b.HasIndex("PlayerId")
                        .HasDatabaseName("ix_match_events_player_id");

                    b.ToTable("match_events", (string)null);
                });

            modelBuilder.Entity("ManagerGame.Domain.MatchResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AwayGoals")
                        .HasColumnType("integer")
                        .HasColumnName("away_goals");

                    b.Property<string>("AwayTeamCountry")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("away_team_country");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_date");

                    b.Property<int>("HomeGoals")
                        .HasColumnType("integer")
                        .HasColumnName("home_goals");

                    b.Property<string>("HomeTeamCountry")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("home_team_country");

                    b.Property<bool>("IsFinished")
                        .HasColumnType("boolean")
                        .HasColumnName("is_finished");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uuid")
                        .HasColumnName("league_id");

                    b.Property<DateTime>("MatchDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("match_date");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.HasKey("Id")
                        .HasName("pk_match_results");

                    b.HasIndex("LeagueId")
                        .HasDatabaseName("ix_match_results_league_id");

                    b.ToTable("match_results", (string)null);
                });

            modelBuilder.Entity("ManagerGame.Domain.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_date");

                    b.Property<bool>("Eliminated")
                        .HasColumnType("boolean")
                        .HasColumnName("eliminated");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.HasKey("Id")
                        .HasName("pk_players");

                    b.ToTable("players", (string)null);
                });

            modelBuilder.Entity("ManagerGame.Domain.StartingEleven", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_date");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_locked");

                    b.Property<string>("MatchRound")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("match_round");

                    b.Property<int>("PointsEarned")
                        .HasColumnType("integer")
                        .HasColumnName("points_earned");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.HasKey("Id")
                        .HasName("pk_starting_elevens");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_starting_elevens_team_id");

                    b.ToTable("starting_elevens", (string)null);
                });

            modelBuilder.Entity("ManagerGame.Domain.StartingElevenPlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_date");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<Guid>("StartingElevenId")
                        .HasColumnType("uuid")
                        .HasColumnName("starting_eleven_id");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.HasKey("Id")
                        .HasName("pk_starting_eleven_player");

                    b.HasIndex("PlayerId")
                        .HasDatabaseName("ix_starting_eleven_player_player_id");

                    b.HasIndex("StartingElevenId")
                        .HasDatabaseName("ix_starting_eleven_player_starting_eleven_id");

                    b.ToTable("starting_eleven_player", (string)null);
                });

            modelBuilder.Entity("ManagerGame.Domain.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_date");

                    b.Property<Guid?>("LeagueId")
                        .HasColumnType("uuid")
                        .HasColumnName("league_id");

                    b.Property<Guid>("ManagerId")
                        .HasColumnType("uuid")
                        .HasColumnName("manager_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("TotalPoints")
                        .HasColumnType("integer")
                        .HasColumnName("total_points");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.HasKey("Id")
                        .HasName("pk_teams");

                    b.HasIndex("LeagueId")
                        .HasDatabaseName("ix_teams_league_id");

                    b.HasIndex("ManagerId")
                        .HasDatabaseName("ix_teams_manager_id");

                    b.ToTable("teams", (string)null);
                });

            modelBuilder.Entity("ManagerGame.Domain.TeamPlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_date");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.HasKey("Id")
                        .HasName("pk_team_player");

                    b.HasIndex("PlayerId")
                        .HasDatabaseName("ix_team_player_player_id");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_team_player_team_id");

                    b.ToTable("team_player", (string)null);
                });

            modelBuilder.Entity("ManagerGame.Domain.Draft", b =>
                {
                    b.HasOne("ManagerGame.Domain.League", "League")
                        .WithMany("Drafts")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_drafts_leagues_league_id");

                    b.OwnsOne("ManagerGame.Domain.DraftOrder", "DraftOrder", b1 =>
                        {
                            b1.Property<Guid>("DraftId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int>("_current")
                                .HasColumnType("integer")
                                .HasColumnName("draftOrderCurrent");

                            b1.Property<int>("_previous")
                                .HasColumnType("integer")
                                .HasColumnName("draftOrderPrevious");

                            b1.HasKey("DraftId");

                            b1.ToTable("drafts");

                            b1.WithOwner()
                                .HasForeignKey("DraftId")
                                .HasConstraintName("fk_drafts_drafts_id");
                        });

                    b.Navigation("DraftOrder")
                        .IsRequired();

                    b.Navigation("League");
                });

            modelBuilder.Entity("ManagerGame.Domain.LeagueSettings", b =>
                {
                    b.HasOne("ManagerGame.Domain.League", "League")
                        .WithOne("Settings")
                        .HasForeignKey("ManagerGame.Domain.LeagueSettings", "LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_league_settings_leagues_league_id");

                    b.Navigation("League");
                });

            modelBuilder.Entity("ManagerGame.Domain.MatchEvent", b =>
                {
                    b.HasOne("ManagerGame.Domain.MatchResult", "Match")
                        .WithMany("MatchEvents")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_match_events_match_results_match_id");

                    b.HasOne("ManagerGame.Domain.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_match_events_players_player_id");

                    b.Navigation("Match");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("ManagerGame.Domain.MatchResult", b =>
                {
                    b.HasOne("ManagerGame.Domain.League", "League")
                        .WithMany("MatchResults")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_match_results_leagues_league_id");

                    b.Navigation("League");
                });

            modelBuilder.Entity("ManagerGame.Domain.StartingEleven", b =>
                {
                    b.HasOne("ManagerGame.Domain.Team", "Team")
                        .WithMany("StartingElevens")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_starting_elevens_teams_team_id");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("ManagerGame.Domain.StartingElevenPlayer", b =>
                {
                    b.HasOne("ManagerGame.Domain.Player", "Player")
                        .WithMany("StartingElevenPlayers")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_starting_eleven_player_players_player_id");

                    b.HasOne("ManagerGame.Domain.StartingEleven", "StartingEleven")
                        .WithMany("SelectedPlayers")
                        .HasForeignKey("StartingElevenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_starting_eleven_player_starting_elevens_starting_eleven_id");

                    b.Navigation("Player");

                    b.Navigation("StartingEleven");
                });

            modelBuilder.Entity("ManagerGame.Domain.Team", b =>
                {
                    b.HasOne("ManagerGame.Domain.League", "League")
                        .WithMany("Teams")
                        .HasForeignKey("LeagueId")
                        .HasConstraintName("fk_teams_leagues_league_id");

                    b.HasOne("ManagerGame.Domain.Manager", null)
                        .WithMany("Teams")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_teams_managers_manager_id");

                    b.Navigation("League");
                });

            modelBuilder.Entity("ManagerGame.Domain.TeamPlayer", b =>
                {
                    b.HasOne("ManagerGame.Domain.Player", "Player")
                        .WithMany("TeamPlayers")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_team_player_players_player_id");

                    b.HasOne("ManagerGame.Domain.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_team_player_teams_team_id");

                    b.Navigation("Player");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("ManagerGame.Domain.League", b =>
                {
                    b.Navigation("Drafts");

                    b.Navigation("MatchResults");

                    b.Navigation("Settings")
                        .IsRequired();

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("ManagerGame.Domain.Manager", b =>
                {
                    b.Navigation("Teams");
                });

            modelBuilder.Entity("ManagerGame.Domain.MatchResult", b =>
                {
                    b.Navigation("MatchEvents");
                });

            modelBuilder.Entity("ManagerGame.Domain.Player", b =>
                {
                    b.Navigation("StartingElevenPlayers");

                    b.Navigation("TeamPlayers");
                });

            modelBuilder.Entity("ManagerGame.Domain.StartingEleven", b =>
                {
                    b.Navigation("SelectedPlayers");
                });

            modelBuilder.Entity("ManagerGame.Domain.Team", b =>
                {
                    b.Navigation("Players");

                    b.Navigation("StartingElevens");
                });
#pragma warning restore 612, 618
        }
    }
}
